### ISSUE TITLE
Error 500 when accessing admin after starting the final container

### ISSUE THREAD

**Issue by tudorbarascu** [jancelin/docker-lizmap#15]
Hi and thanks for your nice work.
Following the exact steps I get:
```
Error 500. A technical error has occured. Sorry for this trouble.
Application log directory is not writable
```
when accessing ``http://localhost/websig/lizmap/www/admin.php``

**Comment by jancelin** [comment]
Hi,
These are the rights to the folder "/home/var_lizmap" that bug.
You have done well this "cp -Apr" to retain the rights when copying /var:

go into lizmap_temp container:
docker exec -it lizmap_temp bash

Copy folders with rights lizmap/var:
cp -avr /var/www/websig/lizmap/var /home/lizmap_var

------
otherwise, look rights to a temporary container and apply to host:
docker exec -it lizmap_temp bash
ls -ln /var/www/websig/lizmap/var
exit
chown "your-ls-result:your-ls-result" /home/lizmap_var

**Comment by tudorbarascu** [comment]
Thanks for the info.
Done exactly as you suggested, still with no results.

By following exactly the steps outlined under ``/home/lizmap_var/`` there is another lizmap_var directory. Is this how you wanted it?
```
$ ls -al /home/lizmap_var/lizmap_var/
total 44
drwxrwxr-x 11 root     www-data 4096 Apr 12 07:39 .
drwxr-xr-x  3 www-data www-data 4096 Apr  4 07:34 ..
drwxrwxr-x  5 www-data www-data 4096 Mar 20 00:14 config
drwxrwxr-x  2 www-data www-data 4096 Mar 20 00:14 db
drwxrwxr-x  2 www-data www-data 4096 Mar 15 18:10 log
drwxrwxr-x  2 www-data www-data 4096 Mar 15 18:10 mails
drwxrwxr-x  8 root     www-data 4096 Mar 15 18:10 overloads
drwxrwxr-x  2 root     www-data 4096 Mar 15 18:10 sessions
drwxrwxr-x  3 root     www-data 4096 Mar 15 18:10 themes
drwxrwxr-x  2 www-data www-data 4096 Mar 15 18:10 uploads
drwxrwxr-x 10 root     www-data 4096 Apr 12 07:39 var
```

**Comment by tudorbarascu** [comment]
Actually, I solved it by doing:
```
cd /home/lizmap_var/lizmap_var/ && mv * ../
```
It's clear that the Readme needs a pull request to fix the path, I'll make it later.
Thanks!

**Comment by MickaelH974** [comment]
Bonjour,

Problème résolu avec la même commande

`cd /home/lizmap_var/lizmap_var/ && mv * ../`

Merci beaucoup.
